name: 'Yarn-cli with chromium'
description: 'Runs any yarn or npm command e.g. yarn test. With a chromium browser installed'
author: nivaldogmelo
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: box
  color: green
